---
name: Publish Release Image
'on':
  release:
    branches:
    - develop
    types:
    - published
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out GitHub Repo
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
      uses: actions/checkout@v2
    - name: Build and Push to Packages
      env:
        PR: "${{ github.event.pull_request.number }}"
        SHA: "${{ github.event.pull_request.head.sha }}"
        VER: "${{ github.event.release.tag_name }}"
        DOCKER_ACTOR: "${{ secrets.GHCR_USERNAME }}"
        DOCKER_TOKEN: "${{ secrets.GHCR_TOKEN }}"
      run: "./.github/workflows/scripts/develop_rc_release.sh\n"