---
name: Publish Release Image
'on':
  release:
    branches:
    - main
    - master
    types:
    - published
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
#    - name: Verify merge is develop > main
#      if: github.head_ref != 'develop'
#      run: exit 1 // Must merge from develop > main/master
    - name: Check out GitHub Repo
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
      uses: actions/checkout@v2
    - name: Build and Push to Packages
      env:
        PR: "${{ github.event.pull_request.number }}"
        SHA: "${{ github.event.pull_request.head.sha }}"
        VER: "${{ github.event.release.tag_name }}"
        DOCKER_ACTOR: "${{ secrets.GHCR_USERNAME }}"
        DOCKER_TOKEN: "${{ secrets.GHCR_TOKEN }}"
      run: "./.github/workflows/scripts/prod_release.sh\n"